//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/ProjectMSInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/ProjectMSInputAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ProjectMSInputAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ProjectMSInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ProjectMSInputAction"",
    ""maps"": [
        {
            ""name"": ""TouchControl"",
            ""id"": ""6629b23b-3559-4754-bd10-ce8b79223ca5"",
            ""actions"": [
                {
                    ""name"": ""PrimaryContact"",
                    ""type"": ""Value"",
                    ""id"": ""b360d50e-209d-4208-a174-0e453822d48f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryPosition"",
                    ""type"": ""Value"",
                    ""id"": ""8d08dc0a-01cc-43ce-9421-c4ed0f0aecbe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5074bc15-7215-4661-878c-6a97b7532465"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""574aea17-e2a3-4734-85e1-275817fc828a"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerControl"",
            ""id"": ""e2d7a932-56c6-4598-82b1-2a340b6a3ffc"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""d72b5230-b973-47e9-aed5-8601a3c28c30"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LaunchMissile"",
                    ""type"": ""Button"",
                    ""id"": ""67437061-8655-4b9e-83ee-3fd2e3d58ffa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""34ce90f0-7660-4ed2-9ec4-5fa91ebeadcb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EmerEvac"",
                    ""type"": ""Button"",
                    ""id"": ""c0b592cc-8630-44bb-a56f-69244081ffc3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thruster"",
                    ""type"": ""Button"",
                    ""id"": ""9dfd565a-4bbb-4a1b-b945-b5f662b64364"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Obliterator"",
                    ""type"": ""Button"",
                    ""id"": ""3daf3b39-db0d-4d1b-869e-85bbe05cb277"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMinimap"",
                    ""type"": ""Button"",
                    ""id"": ""d6a4b222-3172-4194-ade9-4963226d68f9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7dfb88eb-c31a-4c45-83fa-b61a36bb30ed"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4a48db99-95a7-4c99-93bf-a6311fb86965"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""32ef3d44-8f1e-4995-9159-bf40949d9c2c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""78450b3b-e898-43bd-9d52-4fd35900abd4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4256d627-fbc3-4ac9-a9d6-b16d136ee0b6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""90e00e4d-fc92-4530-9753-1c4bc3e93b7c"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ab030f0-09ca-4d04-8387-91748d250719"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaunchMissile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33b1fa47-4b15-4132-b755-c4971aea4ff4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0362cd27-0780-497c-8f77-623ab8a1a1b5"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EmerEvac"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3801e82e-0076-415c-92d4-c14064f0542e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thruster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65a8e38c-a51d-46b9-a76b-f690d7e7ba2b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thruster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d49a749d-6f40-4cbf-97d6-c1d20aec7f42"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Obliterator"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""603b55fa-e8b3-4916-b947-2805ec626cf4"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMinimap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GameControl"",
            ""id"": ""c18f1c56-ab06-43f3-b30b-96581e05598f"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""90f1651f-9521-4496-922d-818fcb4888e0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuExpedition"",
                    ""type"": ""Button"",
                    ""id"": ""b728a89a-ea8e-4786-918b-1116600ad7f8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuUpgrade"",
                    ""type"": ""Button"",
                    ""id"": ""c172e001-aa17-4206-a944-64e93ff9bdaa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuCargo"",
                    ""type"": ""Button"",
                    ""id"": ""51c2d271-2f1e-4f6c-8fcc-0caa00484bb7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""c9da1d71-20d1-4ec0-8ead-c25af5d10859"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Deny"",
                    ""type"": ""Button"",
                    ""id"": ""c9ae9ea0-7e8f-48da-a867-02d6fb58cdad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpgradeContext"",
                    ""type"": ""Button"",
                    ""id"": ""93b61384-19d5-4834-8bf6-635c96b0584b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseEmerEvac"",
                    ""type"": ""Button"",
                    ""id"": ""f2a2a109-89a9-4ff7-9237-980323bb77e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseThruster"",
                    ""type"": ""Button"",
                    ""id"": ""86520051-6c17-4cf9-a3fe-b65af90401ca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseObliterator"",
                    ""type"": ""Button"",
                    ""id"": ""5685632e-2428-4a9b-a6bb-0123a03370c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReadDetails"",
                    ""type"": ""Button"",
                    ""id"": ""59b23905-5aa3-4f60-a99c-bd059080c098"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a15f50f5-d79d-4aa4-8d9b-2ff2c8e4e483"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bf8d020-5d9c-4f11-9546-7f41ada87d86"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuExpedition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9d14336-470d-46a1-a86e-ea7a9b846cdd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuUpgrade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30610641-e2fb-40bc-b923-dcefe44f2698"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuCargo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""278c6afc-f67d-4909-ae68-1820319a4d41"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74ddf208-b47f-4342-998c-8cc28058496e"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deny"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""024a7c20-1ab6-46cc-ba09-705aae93f09f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeContext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72f3bedf-b874-4c6e-8828-570058e84680"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeContext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ccfa098-8c29-44a4-84a2-9284cbe7aeb4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeContext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""685fb804-e8ed-4a39-b7ee-571479fd7986"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeContext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""803f896d-2c07-4168-b015-6cd4d6c9d79b"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseEmerEvac"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82443f07-7eb6-4980-8833-bfebcf49574d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseThruster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e28b5c5f-73d2-4502-baaa-70cdc77fd173"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseObliterator"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""194fb7e1-d32c-40b6-9500-64496054f30f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReadDetails"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""id"": ""93843d23-eff4-4c61-ba11-8311092d0c76"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""e796271a-089b-4fb4-b4d7-aa2a6b9d19b9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ff6f70c-25b1-4d41-931d-dc59d06052d0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TouchControl
        m_TouchControl = asset.FindActionMap("TouchControl", throwIfNotFound: true);
        m_TouchControl_PrimaryContact = m_TouchControl.FindAction("PrimaryContact", throwIfNotFound: true);
        m_TouchControl_PrimaryPosition = m_TouchControl.FindAction("PrimaryPosition", throwIfNotFound: true);
        // PlayerControl
        m_PlayerControl = asset.FindActionMap("PlayerControl", throwIfNotFound: true);
        m_PlayerControl_Movement = m_PlayerControl.FindAction("Movement", throwIfNotFound: true);
        m_PlayerControl_LaunchMissile = m_PlayerControl.FindAction("LaunchMissile", throwIfNotFound: true);
        m_PlayerControl_Interaction = m_PlayerControl.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerControl_EmerEvac = m_PlayerControl.FindAction("EmerEvac", throwIfNotFound: true);
        m_PlayerControl_Thruster = m_PlayerControl.FindAction("Thruster", throwIfNotFound: true);
        m_PlayerControl_Obliterator = m_PlayerControl.FindAction("Obliterator", throwIfNotFound: true);
        m_PlayerControl_OpenMinimap = m_PlayerControl.FindAction("OpenMinimap", throwIfNotFound: true);
        // GameControl
        m_GameControl = asset.FindActionMap("GameControl", throwIfNotFound: true);
        m_GameControl_Pause = m_GameControl.FindAction("Pause", throwIfNotFound: true);
        m_GameControl_MenuExpedition = m_GameControl.FindAction("MenuExpedition", throwIfNotFound: true);
        m_GameControl_MenuUpgrade = m_GameControl.FindAction("MenuUpgrade", throwIfNotFound: true);
        m_GameControl_MenuCargo = m_GameControl.FindAction("MenuCargo", throwIfNotFound: true);
        m_GameControl_Confirm = m_GameControl.FindAction("Confirm", throwIfNotFound: true);
        m_GameControl_Deny = m_GameControl.FindAction("Deny", throwIfNotFound: true);
        m_GameControl_UpgradeContext = m_GameControl.FindAction("UpgradeContext", throwIfNotFound: true);
        m_GameControl_UseEmerEvac = m_GameControl.FindAction("UseEmerEvac", throwIfNotFound: true);
        m_GameControl_UseThruster = m_GameControl.FindAction("UseThruster", throwIfNotFound: true);
        m_GameControl_UseObliterator = m_GameControl.FindAction("UseObliterator", throwIfNotFound: true);
        m_GameControl_ReadDetails = m_GameControl.FindAction("ReadDetails", throwIfNotFound: true);
        // Joystick
        m_Joystick = asset.FindActionMap("Joystick", throwIfNotFound: true);
        m_Joystick_Newaction = m_Joystick.FindAction("New action", throwIfNotFound: true);
    }

    ~@ProjectMSInputAction()
    {
        UnityEngine.Debug.Assert(!m_TouchControl.enabled, "This will cause a leak and performance issues, ProjectMSInputAction.TouchControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerControl.enabled, "This will cause a leak and performance issues, ProjectMSInputAction.PlayerControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_GameControl.enabled, "This will cause a leak and performance issues, ProjectMSInputAction.GameControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Joystick.enabled, "This will cause a leak and performance issues, ProjectMSInputAction.Joystick.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TouchControl
    private readonly InputActionMap m_TouchControl;
    private List<ITouchControlActions> m_TouchControlActionsCallbackInterfaces = new List<ITouchControlActions>();
    private readonly InputAction m_TouchControl_PrimaryContact;
    private readonly InputAction m_TouchControl_PrimaryPosition;
    /// <summary>
    /// Provides access to input actions defined in input action map "TouchControl".
    /// </summary>
    public struct TouchControlActions
    {
        private @ProjectMSInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TouchControlActions(@ProjectMSInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TouchControl/PrimaryContact".
        /// </summary>
        public InputAction @PrimaryContact => m_Wrapper.m_TouchControl_PrimaryContact;
        /// <summary>
        /// Provides access to the underlying input action "TouchControl/PrimaryPosition".
        /// </summary>
        public InputAction @PrimaryPosition => m_Wrapper.m_TouchControl_PrimaryPosition;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TouchControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TouchControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TouchControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TouchControlActions" />
        public void AddCallbacks(ITouchControlActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchControlActionsCallbackInterfaces.Add(instance);
            @PrimaryContact.started += instance.OnPrimaryContact;
            @PrimaryContact.performed += instance.OnPrimaryContact;
            @PrimaryContact.canceled += instance.OnPrimaryContact;
            @PrimaryPosition.started += instance.OnPrimaryPosition;
            @PrimaryPosition.performed += instance.OnPrimaryPosition;
            @PrimaryPosition.canceled += instance.OnPrimaryPosition;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TouchControlActions" />
        private void UnregisterCallbacks(ITouchControlActions instance)
        {
            @PrimaryContact.started -= instance.OnPrimaryContact;
            @PrimaryContact.performed -= instance.OnPrimaryContact;
            @PrimaryContact.canceled -= instance.OnPrimaryContact;
            @PrimaryPosition.started -= instance.OnPrimaryPosition;
            @PrimaryPosition.performed -= instance.OnPrimaryPosition;
            @PrimaryPosition.canceled -= instance.OnPrimaryPosition;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TouchControlActions.UnregisterCallbacks(ITouchControlActions)" />.
        /// </summary>
        /// <seealso cref="TouchControlActions.UnregisterCallbacks(ITouchControlActions)" />
        public void RemoveCallbacks(ITouchControlActions instance)
        {
            if (m_Wrapper.m_TouchControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TouchControlActions.AddCallbacks(ITouchControlActions)" />
        /// <seealso cref="TouchControlActions.RemoveCallbacks(ITouchControlActions)" />
        /// <seealso cref="TouchControlActions.UnregisterCallbacks(ITouchControlActions)" />
        public void SetCallbacks(ITouchControlActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TouchControlActions" /> instance referencing this action map.
    /// </summary>
    public TouchControlActions @TouchControl => new TouchControlActions(this);

    // PlayerControl
    private readonly InputActionMap m_PlayerControl;
    private List<IPlayerControlActions> m_PlayerControlActionsCallbackInterfaces = new List<IPlayerControlActions>();
    private readonly InputAction m_PlayerControl_Movement;
    private readonly InputAction m_PlayerControl_LaunchMissile;
    private readonly InputAction m_PlayerControl_Interaction;
    private readonly InputAction m_PlayerControl_EmerEvac;
    private readonly InputAction m_PlayerControl_Thruster;
    private readonly InputAction m_PlayerControl_Obliterator;
    private readonly InputAction m_PlayerControl_OpenMinimap;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerControl".
    /// </summary>
    public struct PlayerControlActions
    {
        private @ProjectMSInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerControlActions(@ProjectMSInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/Movement".
        /// </summary>
        public InputAction @Movement => m_Wrapper.m_PlayerControl_Movement;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/LaunchMissile".
        /// </summary>
        public InputAction @LaunchMissile => m_Wrapper.m_PlayerControl_LaunchMissile;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/Interaction".
        /// </summary>
        public InputAction @Interaction => m_Wrapper.m_PlayerControl_Interaction;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/EmerEvac".
        /// </summary>
        public InputAction @EmerEvac => m_Wrapper.m_PlayerControl_EmerEvac;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/Thruster".
        /// </summary>
        public InputAction @Thruster => m_Wrapper.m_PlayerControl_Thruster;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/Obliterator".
        /// </summary>
        public InputAction @Obliterator => m_Wrapper.m_PlayerControl_Obliterator;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/OpenMinimap".
        /// </summary>
        public InputAction @OpenMinimap => m_Wrapper.m_PlayerControl_OpenMinimap;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerControlActions" />
        public void AddCallbacks(IPlayerControlActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @LaunchMissile.started += instance.OnLaunchMissile;
            @LaunchMissile.performed += instance.OnLaunchMissile;
            @LaunchMissile.canceled += instance.OnLaunchMissile;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @EmerEvac.started += instance.OnEmerEvac;
            @EmerEvac.performed += instance.OnEmerEvac;
            @EmerEvac.canceled += instance.OnEmerEvac;
            @Thruster.started += instance.OnThruster;
            @Thruster.performed += instance.OnThruster;
            @Thruster.canceled += instance.OnThruster;
            @Obliterator.started += instance.OnObliterator;
            @Obliterator.performed += instance.OnObliterator;
            @Obliterator.canceled += instance.OnObliterator;
            @OpenMinimap.started += instance.OnOpenMinimap;
            @OpenMinimap.performed += instance.OnOpenMinimap;
            @OpenMinimap.canceled += instance.OnOpenMinimap;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerControlActions" />
        private void UnregisterCallbacks(IPlayerControlActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @LaunchMissile.started -= instance.OnLaunchMissile;
            @LaunchMissile.performed -= instance.OnLaunchMissile;
            @LaunchMissile.canceled -= instance.OnLaunchMissile;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @EmerEvac.started -= instance.OnEmerEvac;
            @EmerEvac.performed -= instance.OnEmerEvac;
            @EmerEvac.canceled -= instance.OnEmerEvac;
            @Thruster.started -= instance.OnThruster;
            @Thruster.performed -= instance.OnThruster;
            @Thruster.canceled -= instance.OnThruster;
            @Obliterator.started -= instance.OnObliterator;
            @Obliterator.performed -= instance.OnObliterator;
            @Obliterator.canceled -= instance.OnObliterator;
            @OpenMinimap.started -= instance.OnOpenMinimap;
            @OpenMinimap.performed -= instance.OnOpenMinimap;
            @OpenMinimap.canceled -= instance.OnOpenMinimap;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerControlActions.UnregisterCallbacks(IPlayerControlActions)" />.
        /// </summary>
        /// <seealso cref="PlayerControlActions.UnregisterCallbacks(IPlayerControlActions)" />
        public void RemoveCallbacks(IPlayerControlActions instance)
        {
            if (m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerControlActions.AddCallbacks(IPlayerControlActions)" />
        /// <seealso cref="PlayerControlActions.RemoveCallbacks(IPlayerControlActions)" />
        /// <seealso cref="PlayerControlActions.UnregisterCallbacks(IPlayerControlActions)" />
        public void SetCallbacks(IPlayerControlActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerControlActions" /> instance referencing this action map.
    /// </summary>
    public PlayerControlActions @PlayerControl => new PlayerControlActions(this);

    // GameControl
    private readonly InputActionMap m_GameControl;
    private List<IGameControlActions> m_GameControlActionsCallbackInterfaces = new List<IGameControlActions>();
    private readonly InputAction m_GameControl_Pause;
    private readonly InputAction m_GameControl_MenuExpedition;
    private readonly InputAction m_GameControl_MenuUpgrade;
    private readonly InputAction m_GameControl_MenuCargo;
    private readonly InputAction m_GameControl_Confirm;
    private readonly InputAction m_GameControl_Deny;
    private readonly InputAction m_GameControl_UpgradeContext;
    private readonly InputAction m_GameControl_UseEmerEvac;
    private readonly InputAction m_GameControl_UseThruster;
    private readonly InputAction m_GameControl_UseObliterator;
    private readonly InputAction m_GameControl_ReadDetails;
    /// <summary>
    /// Provides access to input actions defined in input action map "GameControl".
    /// </summary>
    public struct GameControlActions
    {
        private @ProjectMSInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameControlActions(@ProjectMSInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GameControl/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_GameControl_Pause;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/MenuExpedition".
        /// </summary>
        public InputAction @MenuExpedition => m_Wrapper.m_GameControl_MenuExpedition;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/MenuUpgrade".
        /// </summary>
        public InputAction @MenuUpgrade => m_Wrapper.m_GameControl_MenuUpgrade;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/MenuCargo".
        /// </summary>
        public InputAction @MenuCargo => m_Wrapper.m_GameControl_MenuCargo;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/Confirm".
        /// </summary>
        public InputAction @Confirm => m_Wrapper.m_GameControl_Confirm;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/Deny".
        /// </summary>
        public InputAction @Deny => m_Wrapper.m_GameControl_Deny;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/UpgradeContext".
        /// </summary>
        public InputAction @UpgradeContext => m_Wrapper.m_GameControl_UpgradeContext;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/UseEmerEvac".
        /// </summary>
        public InputAction @UseEmerEvac => m_Wrapper.m_GameControl_UseEmerEvac;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/UseThruster".
        /// </summary>
        public InputAction @UseThruster => m_Wrapper.m_GameControl_UseThruster;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/UseObliterator".
        /// </summary>
        public InputAction @UseObliterator => m_Wrapper.m_GameControl_UseObliterator;
        /// <summary>
        /// Provides access to the underlying input action "GameControl/ReadDetails".
        /// </summary>
        public InputAction @ReadDetails => m_Wrapper.m_GameControl_ReadDetails;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GameControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameControlActions" />
        public void AddCallbacks(IGameControlActions instance)
        {
            if (instance == null || m_Wrapper.m_GameControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameControlActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @MenuExpedition.started += instance.OnMenuExpedition;
            @MenuExpedition.performed += instance.OnMenuExpedition;
            @MenuExpedition.canceled += instance.OnMenuExpedition;
            @MenuUpgrade.started += instance.OnMenuUpgrade;
            @MenuUpgrade.performed += instance.OnMenuUpgrade;
            @MenuUpgrade.canceled += instance.OnMenuUpgrade;
            @MenuCargo.started += instance.OnMenuCargo;
            @MenuCargo.performed += instance.OnMenuCargo;
            @MenuCargo.canceled += instance.OnMenuCargo;
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @Deny.started += instance.OnDeny;
            @Deny.performed += instance.OnDeny;
            @Deny.canceled += instance.OnDeny;
            @UpgradeContext.started += instance.OnUpgradeContext;
            @UpgradeContext.performed += instance.OnUpgradeContext;
            @UpgradeContext.canceled += instance.OnUpgradeContext;
            @UseEmerEvac.started += instance.OnUseEmerEvac;
            @UseEmerEvac.performed += instance.OnUseEmerEvac;
            @UseEmerEvac.canceled += instance.OnUseEmerEvac;
            @UseThruster.started += instance.OnUseThruster;
            @UseThruster.performed += instance.OnUseThruster;
            @UseThruster.canceled += instance.OnUseThruster;
            @UseObliterator.started += instance.OnUseObliterator;
            @UseObliterator.performed += instance.OnUseObliterator;
            @UseObliterator.canceled += instance.OnUseObliterator;
            @ReadDetails.started += instance.OnReadDetails;
            @ReadDetails.performed += instance.OnReadDetails;
            @ReadDetails.canceled += instance.OnReadDetails;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameControlActions" />
        private void UnregisterCallbacks(IGameControlActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @MenuExpedition.started -= instance.OnMenuExpedition;
            @MenuExpedition.performed -= instance.OnMenuExpedition;
            @MenuExpedition.canceled -= instance.OnMenuExpedition;
            @MenuUpgrade.started -= instance.OnMenuUpgrade;
            @MenuUpgrade.performed -= instance.OnMenuUpgrade;
            @MenuUpgrade.canceled -= instance.OnMenuUpgrade;
            @MenuCargo.started -= instance.OnMenuCargo;
            @MenuCargo.performed -= instance.OnMenuCargo;
            @MenuCargo.canceled -= instance.OnMenuCargo;
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @Deny.started -= instance.OnDeny;
            @Deny.performed -= instance.OnDeny;
            @Deny.canceled -= instance.OnDeny;
            @UpgradeContext.started -= instance.OnUpgradeContext;
            @UpgradeContext.performed -= instance.OnUpgradeContext;
            @UpgradeContext.canceled -= instance.OnUpgradeContext;
            @UseEmerEvac.started -= instance.OnUseEmerEvac;
            @UseEmerEvac.performed -= instance.OnUseEmerEvac;
            @UseEmerEvac.canceled -= instance.OnUseEmerEvac;
            @UseThruster.started -= instance.OnUseThruster;
            @UseThruster.performed -= instance.OnUseThruster;
            @UseThruster.canceled -= instance.OnUseThruster;
            @UseObliterator.started -= instance.OnUseObliterator;
            @UseObliterator.performed -= instance.OnUseObliterator;
            @UseObliterator.canceled -= instance.OnUseObliterator;
            @ReadDetails.started -= instance.OnReadDetails;
            @ReadDetails.performed -= instance.OnReadDetails;
            @ReadDetails.canceled -= instance.OnReadDetails;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameControlActions.UnregisterCallbacks(IGameControlActions)" />.
        /// </summary>
        /// <seealso cref="GameControlActions.UnregisterCallbacks(IGameControlActions)" />
        public void RemoveCallbacks(IGameControlActions instance)
        {
            if (m_Wrapper.m_GameControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameControlActions.AddCallbacks(IGameControlActions)" />
        /// <seealso cref="GameControlActions.RemoveCallbacks(IGameControlActions)" />
        /// <seealso cref="GameControlActions.UnregisterCallbacks(IGameControlActions)" />
        public void SetCallbacks(IGameControlActions instance)
        {
            foreach (var item in m_Wrapper.m_GameControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameControlActions" /> instance referencing this action map.
    /// </summary>
    public GameControlActions @GameControl => new GameControlActions(this);

    // Joystick
    private readonly InputActionMap m_Joystick;
    private List<IJoystickActions> m_JoystickActionsCallbackInterfaces = new List<IJoystickActions>();
    private readonly InputAction m_Joystick_Newaction;
    /// <summary>
    /// Provides access to input actions defined in input action map "Joystick".
    /// </summary>
    public struct JoystickActions
    {
        private @ProjectMSInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public JoystickActions(@ProjectMSInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Joystick/Newaction".
        /// </summary>
        public InputAction @Newaction => m_Wrapper.m_Joystick_Newaction;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Joystick; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="JoystickActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(JoystickActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="JoystickActions" />
        public void AddCallbacks(IJoystickActions instance)
        {
            if (instance == null || m_Wrapper.m_JoystickActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JoystickActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="JoystickActions" />
        private void UnregisterCallbacks(IJoystickActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="JoystickActions.UnregisterCallbacks(IJoystickActions)" />.
        /// </summary>
        /// <seealso cref="JoystickActions.UnregisterCallbacks(IJoystickActions)" />
        public void RemoveCallbacks(IJoystickActions instance)
        {
            if (m_Wrapper.m_JoystickActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="JoystickActions.AddCallbacks(IJoystickActions)" />
        /// <seealso cref="JoystickActions.RemoveCallbacks(IJoystickActions)" />
        /// <seealso cref="JoystickActions.UnregisterCallbacks(IJoystickActions)" />
        public void SetCallbacks(IJoystickActions instance)
        {
            foreach (var item in m_Wrapper.m_JoystickActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JoystickActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="JoystickActions" /> instance referencing this action map.
    /// </summary>
    public JoystickActions @Joystick => new JoystickActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TouchControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TouchControlActions.AddCallbacks(ITouchControlActions)" />
    /// <seealso cref="TouchControlActions.RemoveCallbacks(ITouchControlActions)" />
    public interface ITouchControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "PrimaryContact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryContact(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrimaryPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryPosition(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerControlActions.AddCallbacks(IPlayerControlActions)" />
    /// <seealso cref="PlayerControlActions.RemoveCallbacks(IPlayerControlActions)" />
    public interface IPlayerControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "Movement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LaunchMissile" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLaunchMissile(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Interaction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteraction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EmerEvac" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEmerEvac(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Thruster" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThruster(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Obliterator" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnObliterator(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenMinimap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenMinimap(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GameControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameControlActions.AddCallbacks(IGameControlActions)" />
    /// <seealso cref="GameControlActions.RemoveCallbacks(IGameControlActions)" />
    public interface IGameControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MenuExpedition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMenuExpedition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MenuUpgrade" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMenuUpgrade(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MenuCargo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMenuCargo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Confirm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConfirm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Deny" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDeny(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UpgradeContext" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUpgradeContext(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseEmerEvac" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseEmerEvac(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseThruster" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseThruster(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseObliterator" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseObliterator(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ReadDetails" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReadDetails(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Joystick" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="JoystickActions.AddCallbacks(IJoystickActions)" />
    /// <seealso cref="JoystickActions.RemoveCallbacks(IJoystickActions)" />
    public interface IJoystickActions
    {
        /// <summary>
        /// Method invoked when associated input action "New action" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNewaction(InputAction.CallbackContext context);
    }
}
